spring:
  application:
    name: ProductService
  data:
    redis:
      port: 6379
      host: localhost
      cache:
        type: redis
    mongodb:
      uri: mongodb://localhost:27017/OderyProduct
server:
  port: 8092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka