spring:
  data:
    mongodb:
      database: OrderyOrder
      port: 27017
      username:
      password:
      host: localhost
  application:
    name: OderService
  rabbitmq:
  host: localhost
  port: 5672
  username: username
  password: password
server:
  port: 8091